name: Build nightly container image
on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      file_to_build: Dockerfile
      platforms: linux/arm64
      use_native_arm64_builder: false
      cache: false
    secrets: inherit